# Generated by Django 3.1.1 on 2020-12-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201119_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=1024, unique=True, verbose_name='Ttile'),
        ),
    ]
