# Generated by Django 3.1.1 on 2020-10-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='state',
            new_name='is_active',
        ),
    ]
