# Generated by Django 3.1.1 on 2020-09-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200925_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='firstname',
            field=models.CharField(max_length=200, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='Last login'),
        ),
        migrations.AlterField(
            model_name='account',
            name='lastname',
            field=models.CharField(max_length=200, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='bookincart',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Book count'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='state',
            field=models.BooleanField(default=False, verbose_name='State'),
        ),
    ]
