# Generated by Django 3.1.1 on 2020-10-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201006_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='bookreview',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
