# Generated by Django 3.1.1 on 2020-09-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200921_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, max_length=150, verbose_name='user name'),
        ),
    ]
