# Generated by Django 3.1.1 on 2020-10-30 02:23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201027_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='unique_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
