# Generated by Django 3.1.1 on 2020-09-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200920_1214'),
        ('users', '0008_remove_account_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartBook',
            new_name='BookInCart',
        ),
    ]
