# Generated by Django 3.1.1 on 2020-09-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20200925_1950'),
        ('users', '0009_auto_20200928_0955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='BookReview',
        ),
    ]
