# Generated by Django 3.1.1 on 2020-09-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200928_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='reply',
        ),
    ]
