# Generated by Django 3.1.1 on 2020-11-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201105_0903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookReview',
        ),
    ]
