# Generated by Django 3.1.1 on 2020-12-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20201213_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='stripe_id',
        ),
    ]
