# Generated by Django 3.1.1 on 2020-09-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.CharField(choices=[('E-BK', 'E-Book'), ('HD-CVR', 'Hardcover'), ('PPR-BCK', 'Paperback')], default=None, max_length=7),
            preserve_default=False,
        ),
    ]
