# Generated by Django 3.1.1 on 2020-09-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200920_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='address',
            field=models.TextField(max_length=150),
        ),
    ]
