# Generated by Django 3.1.1 on 2020-09-19 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200919_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.warehouse')),
            ],
        ),
    ]
