# Generated by Django 3.1.1 on 2020-09-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200920_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
