# Generated by Django 3.1.1 on 2020-09-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20200922_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='url',
            new_name='publisher_url',
        ),
    ]
