# Generated by Django 3.1.1 on 2020-09-25 19:50

import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20200923_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='address',
            field=models.TextField(max_length=150, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Author name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('THR', 'Thriller'), ('FNSY', 'Fantasy'), ('RMCE', 'Romance'), ('AVTRE', 'Adventure')], max_length=5, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.CharField(choices=[('E-BK', 'E-Book'), ('HD-CVR', 'Hardcover'), ('PPR-BCK', 'Paperback')], max_length=7, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.TextField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Publisher name'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.TextField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='warehousebook',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Book count'),
        ),
    ]
