# Generated by Django 3.1.1 on 2020-10-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20201019_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Update'),
        ),
        migrations.AlterField(
            model_name='image',
            name='book_cover',
            field=models.ImageField(upload_to='images/', verbose_name='Book cover'),
        ),
    ]
