# Generated by Django 3.1.1 on 2020-11-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20201030_0228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
