# Generated by Django 3.1.1 on 2020-12-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_author_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
