# Generated by Django 3.1.1 on 2020-12-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20201213_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
    ]
