# Generated by Django 3.1.1 on 2020-12-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20201219_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookincart',
            old_name='count',
            new_name='quantity',
        ),
    ]
