# Generated by Django 3.0.4 on 2021-03-20 12:41

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_auto_20210215_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='Phone number'),
        ),
    ]
