# Generated by Django 3.0.4 on 2021-04-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_auto_20210320_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcomment',
            options={},
        ),
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
        migrations.AlterModelTable(
            name='bookcomment',
            table='book_comment',
        ),
        migrations.AlterModelTable(
            name='bookimage',
            table='book_image',
        ),
        migrations.AlterModelTable(
            name='bookincart',
            table='book_in_cart',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='publisher',
        ),
        migrations.AlterModelTable(
            name='warehouse',
            table='warehouse',
        ),
        migrations.AlterModelTable(
            name='warehousebook',
            table='warehouse_book',
        ),
    ]
