# Generated by Django 3.0.4 on 2021-04-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_auto_20210425_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='Title'),
        ),
    ]
