# Generated by Django 3.0.4 on 2021-04-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0031_auto_20210426_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, verbose_name='ISBN'),
        ),
    ]
